services:
  qground:
    image: ${IMAGE_NAME}:${TAG_DEPLOY}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - IMAGE_NAME=${IMAGE_NAME}
        - TAG_BUILD=${TAG_BUILD}

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1    

    privileged: true

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw


  qgroundbuild:
    image: ${IMAGE_NAME}:${TAG_BUILD}
    build:
      context: ./qgroundcontrol
      dockerfile: ./deploy/docker/Dockerfile-build-linux

    container_name: ${CONTAINER_NAME}

    command: "/bin/bash"

    volumes:
      - ${PWD}/qgroundcontrol:/project/source
      - ${PWD}/qgroundcontrol/build:/project/build

    